version: '3.9'
services:
  react:
    stdin_open: true
    container_name: react
    build: ./frontend
    volumes:
     - ./workDir/frontend:/var/www/frontend/:cached
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - network_infrastructure
#    command: npm start

  MySQLDB:
    image: mysql:latest
    container_name: mysql_database
    command: [ --default-authentication-plugin=caching_sha2_password ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mtb
      MYSQL_ALLOW_EMPTY_PASSWORD:
#      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - /var/lib/mysql/
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - network_infrastructure

  symfony:
    build: ./backend
    container_name: symfony
    ports:
      - 9001:9001
    volumes:
      - ./workDir/backend/:/var/www/symfony:cached
      - ./workDir/backend/logs:/var/www/symfony/logs:cached
    links:
#      - MongoDB
      - MySQLDB
#    extra_hosts:
#      - docker-host.localhost:127.0.0.1
    networks:
      - network_infrastructure

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    links:
      - symfony
      - react
    volumes:
      - ./workDir/backend/:/var/www/symfony:cached
      - ./workDir/frontend/:/var/www/frontend:cached
      - ./workDir/logs/:/var/log/nginx:cached
    networks:
      - network_infrastructure

networks:
  network_infrastructure:
    name: network_infrastructure
