version: '3'

services:

  database:
    container_name: database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mtb
      MYSQL_USER: root
    ports:
      - "3306:3306"
    networks:
      - mtb-network
    volumes:
      - ./mysql:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mtb-network
    depends_on:
      - database
    volumes:
      - ./app

volumes:
  mtb-data:


networks:
  mtb-network:
